runtime: nodejs22
instance_class: F1
env: standard 

env_variables:
  DB_HOST: "ease-expense:australia-southeast1:easeexpensedb"
  DB_PORT: 5432
  DB_USER: "rootapurv"
  DB_PASSWORD: "Apurv@05"
  DB_NAME: "expense_tracker"
  PORT: 4000
  JWT_SECRET: "This is expense tracker application & I am Apurv!"